#!/bin/bash

# This is a 'build' action hook script. This script must be executable
# and will be run by the S2I process after the original S2I 'assemble'
# script has been run. This hook is to allow a user to run additional
# build steps which may need the source code or build artefacts in
# place, or to setup any data required for the application.

set -eo pipefail

# Dump out the set of environment variables which were used by the build.

echo " -----> Initial environment variables set by builder image."

env

# Dump out the name of the current working directory.

echo " -----> Current working directory."

pwd

# Dump out the contents of the current working directory.

echo " -----> Contents of the current working directory after build run."

ls -R .

echo " -----> Copy the additional libraries to KIE-Server."
cp $S2I_SOURCE_PATH/.s2i/contrib/client-onboarding-query-mapper-1.0.0-SNAPSHOT.jar $JBOSS_HOME/standalone/deployments/kie-server.war/WEB-INF/lib/client-onboarding-query-mapper-1.0.0-SNAPSHOT.jar
cp $S2I_SOURCE_PATH/.s2i/contrib/kie-server-services-advanced-query-registration-6.5.0.Final-redhat-15.jar $JBOSS_HOME/standalone/deployments/kie-server.war/WEB-INF/lib/kie-server-services-advanced-query-registration-6.5.0.Final-redhat-15.jar
