package com.redhat.bpms.demo.fsi.onboarding.model;

import java.util.ArrayList;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Documents implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label(value = "Documents")
   private java.util.List<org.jbpm.document.Document> documents = new ArrayList<>();

   public Documents()
   {
   }

   public java.util.List<org.jbpm.document.Document> getDocuments()
   {
      return this.documents;
   }

   public void setDocuments(
         java.util.List<org.jbpm.document.Document> documents)
   {
      this.documents = documents;
   }

   public Documents(
         java.util.List<org.jbpm.document.Document> documents)
   {
      this.documents = documents;
   }
   
   public void addDocument(org.jbpm.document.Document document) {
       documents.add(document);
   }

}