package com.redhat.bpms.demo.fsi.onboarding.model;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class RequiredDocuments implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public RequiredDocuments() {
    }

}